### ISSUE TITLE
Search App - Road Map

### ISSUE THREAD

**Issue by habib535** [StarcounterApps/Search#9]
This is a Road Map for all the functionalities / features in the Search app. The bullets are presented in the priority order (1 being the highest).

1. [x] 1. Create the basic search app -  https://github.com/StarcounterApps/Search/issues/1
2. [x] 2. Implement Keyboard arrow navigation in the search results -  https://github.com/StarcounterApps/Search/issues/4
3. [x] 3. Implement pagination on Search All page - https://github.com/StarcounterApps/Search/issues/3
4. [x] 4. Release the initial version and deploy it at inside.starcounter.com - https://github.com/StarcounterApps/Search/issues/8
5. [x] 5. Replace hard-coded queries from code - https://github.com/StarcounterApps/Search/issues/6
6. [x] 6. Pinning of search results - https://github.com/StarcounterApps/Search/issues/7
7. [x] 7. Multiple input fields - Advance search - https://github.com/StarcounterApps/Search/issues/5
